[metadata]
name = "channels"
description = "Select a television channel"
requirements = ["tv", "syncat"]

[source]
command = ["tv list-channels"]

[preview]
command = "syncat -n ${XDG_CONFIG_HOME:-$HOME/.config}/television/cable/{}.toml"

[keybindings]
enter = "actions:channel-enter"

[actions.channel-enter]
description = "Enter a television channel"
command = "tv {}"
mode = "execute"

